version: '3.9'

services:

  llamawhisperer:
    container_name: llamawhisperer
    restart: unless-stopped
    build: .
    volumes:
      - ./pkg/storage/init:/src/pkg/storage/init

    ports:
      - "8079:8079"
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  mongo-express:
    container_name: mongoexp
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
