version: '3.9'

services:
  redis:
    restart: unless-stopped
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/redis/redis:/root/redis
      - /usr/local/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=llamazoo
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
  
  llamawhisperer:
    container_name: llamawhisperer
    restart: unless-stopped
    build: .
    ports:
      - "8079:8079"
    depends_on:
      - redis

  