
download_big:
	huggingface-cli download bartowski/Llama-3.1-8B-Ultra-Instruct-GGUF --include "Llama-3.1-8B-Ultra-Instruct-Q6_K.gguf" --local-dir ./models 

download_small:
	huggingface-cli download bartowski/Llama-3.2-1B-Instruct-GGUF --include "Llama-3.2-1B-Instruct-Q8_0.gguf" --local-dir ./models
download:
	download_small download_big